### ISSUE TITLE
Missing utility script dumpgenerator.py

### ISSUE THREAD

**Issue by GreenReaper** [elsiehupp/wikitools3#2]
I wanted to backup [my WBStack-hosted Wikibase](https://furry.wiki.opencura.com), the information of which is stored in JSON blobs as page content.

I managed to scrape together the necessary FreeBSD packages to get Wikiteams' [dumpgenerator.py](https://github.com/WikiTeam/wikiteam/blob/master/dumpgenerator.py)  working with Python 2.7. However, this is not a solution that can be maintained, or recommended, as they are no longer available via package managers.

I tried installing poetry and wikitools3. However, no dumpgenerator.py exists, and I see it's not in the repo yet - maybe it's not even in scope, considering this is a lower-level library that wikiteam relies on. Perhaps [this file](https://github.com/WikiTeam/wikiteam/blob/ec62f3456beac488c4598415ff244019ab8a9fbc/dumpgenerator.py) from [this pull request](https://github.com/WikiTeam/wikiteam/pull/409) is required?

I appreciate it may not be the priority for Wikiteam's own use, and it's a pretty big script in relation to the API itself - however it's [the recommended approach for backing up a third-party-hosted MediaWiki](https://www.mediawiki.org/wiki/Manual:Backing_up_a_wiki#Without_shell_access_to_the_server), so it would be useful if it could be adapted for Python 3, and that could be rolled out.

**Comment by GreenReaper** [comment]
This seems to actually be addressed by the higher-level [elsiehupp/wikiteam:python3](https://github.com/elsiehupp/wikiteam/tree/python3), though [I had to tweak it to save the XML](https://github.com/WikiTeam/wikiteam/issues/395#issuecomment-926960900).

**Comment by elsiehupp** [comment]
Hi @GreenReaper—thanks for taking the time to write detailed feedback. I am not actually an official maintainer of @wikiteam, though if I ever finish all of peripheral parts of porting it to Python 3 I might end up being one. I’ll respond further on the other thread.
