### ISSUE TITLE
Still python 2 code remains, is being published

### ISSUE THREAD

**Issue by tjoneslo** [elsiehupp/wikitools3#3]
https://github.com/elsiehupp/wikitools3/blob/master/wikitools3/wiki.py#L79

In Py3, this should be urllib.parse.urlparse(), the use of urllib.parse() is Py2 code and does not work with any version of Py3.

**Comment by kdave** [comment]
There are way more problems regarding urllib.request, eg. build_opener, all the urllib.HTTP* constants. My test scripts (inherited from py2 version) also leads to "TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str." unless I quote b"" all request strings. I'll try to send a pull request once I get it all working.

**Comment by tjoneslo** [comment]
I took another look. The python3 branch has the correct code and works with Python3 correctly. So all you should need to do is merge the python3 branch into main and re-publish the PyPi package.

**Comment by elsiehupp** [comment]
Hi! I don’t know why, but I’m not getting auto-subscribed to issues on my own repositories. I will try and take care of this ASAP. Thanks for bringing it to my attention!

**Comment by elsiehupp** [comment]
Hi @tjoneslo and @kdave—I updated the `urllib` syntax for [the `v3.0.1` Release](https://github.com/elsiehupp/wikitools3/releases/tag/v3.0.1). You can download the release code [from GitHub](https://github.com/elsiehupp/wikitools3/releases/tag/v3.0.1) or [install via PyPI](https://pypi.org/project/wikitools3/3.0.1/) if you'd like. Please don't hesitate to let me know if there's anything else I missed, and thank you again for bringing this to my attention!
